// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// autocor
double autocor(NumericVector ts);
RcppExport SEXP RandomThinning_autocor(SEXP tsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type ts(tsSEXP);
    __result = Rcpp::wrap(autocor(ts));
    return __result;
END_RCPP
}
// generateRandomSignal
NumericVector generateRandomSignal(int m, double sac, int maxcounter, double margin);
RcppExport SEXP RandomThinning_generateRandomSignal(SEXP mSEXP, SEXP sacSEXP, SEXP maxcounterSEXP, SEXP marginSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type sac(sacSEXP);
    Rcpp::traits::input_parameter< int >::type maxcounter(maxcounterSEXP);
    Rcpp::traits::input_parameter< double >::type margin(marginSEXP);
    __result = Rcpp::wrap(generateRandomSignal(m, sac, maxcounter, margin));
    return __result;
END_RCPP
}
// rangeTestFinitesOnly
double rangeTestFinitesOnly(NumericVector ts, NumericVector its, int p);
RcppExport SEXP RandomThinning_rangeTestFinitesOnly(SEXP tsSEXP, SEXP itsSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type ts(tsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type its(itsSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    __result = Rcpp::wrap(rangeTestFinitesOnly(ts, its, p));
    return __result;
END_RCPP
}
// rangeTestGeneral
List rangeTestGeneral(NumericVector ts, NumericVector its, int p);
RcppExport SEXP RandomThinning_rangeTestGeneral(SEXP tsSEXP, SEXP itsSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type ts(tsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type its(itsSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    __result = Rcpp::wrap(rangeTestGeneral(ts, its, p));
    return __result;
END_RCPP
}
